org: sergiohidalgocaceres
app: example01
service: lambda-typescript

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, "dev"}

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false

functions:
  registerUser:
    handler: ./src/handlers/index.register